development: 
  adapter: postgresql
  database: figcode-development
  pool: 5
  timeout: 5000

test: 
  adapter: postgresql
  database: figcode-development
  pool: 5
  timeout: 5000

production: 
  adapter: postgresql
  database: figcode-development
  pool: 5
  timeout: 5000


